fix: update allowed-endpoints (#5461)
Add playwright.download.prss.microsoft.com and cdn.playwright.dev in
allowed-endpoints to fix the following failure when installing
playwright:

Downloading Chromium 143.0.7499.4 (playwright build v1200) from https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-linux.zip
(node:3714) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: connect ECONNREFUSED 54.185.253.63:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '54.185.253.63',
  port: 443
}

Also add v4.mirror.cveb.in:443 to fix the same kind of issue:

ClientConnectorError: Cannot connect to host v4.mirror.cveb.in:443 ssl:default
[Connect call failed ('54.185.253.63', 443)]

All those issues are probably raised because ubuntu-latest is used
instead of intel-ubuntu-latest since switch to ossf

Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>